### ISSUE TITLE
I do not get outputs for the second IO_method

### ISSUE THREAD

**Issue by mastaia** [ChrisFairless/nccs-supply-chain#68]
On the current main branch, there should be everything implemented to work for both IO approaches. But I only get the output for the first one in the list. Probably there 1 statement of "output already exists", then skip placed too early, such that the second Io approach does not get calculated or produce output. 

I tried to check a bit where it could happen but maybe @ChrisFairless you are quicker in spotting it. 

Probably somewhere here, where the direct output already exists, okay to not compute this again but nor sure if it then really goes into the indirect caclulation
<img width="862" alt="image" src="https://github.com/user-attachments/assets/0683adaf-2394-4b1c-b7c3-a31bff6af2d3">

**Comment by ChrisFairless** [comment]
Thanks for flagging this. You're exactly right in where the bug is.
